#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num1 = 0
num2 = 1
a = 0
while num1 <= 4000000:
    print(num1)
    numT = num1 + num2
    num1 = num2
    num2 = numT

    if num1 % 2 == 0 and num1 < 4000000:
        a = a + num1
print("Sum of the even-valued terms:" + str(a))



